[package]
name = "downapk"
version = "0.2.0"
edition = "2021"
categories = ["command-line-utilities"]
description = "Program to download APKs of given Android package"
homepage = "https://github.com/rabilrbl/downapk"
keywords = ["apk", "android", "download", "cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rabilrbl/downapk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
console = "0.15.8"
indicatif = "0.17.7"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11" }
scraper = "0.18.1"
serde_json = "1.0.111"
tokio = { version = "1.35", features = ["full"] }

[profile.release]
strip = true

[target.'cfg(target_arch = "aarch64")']
pre-build = "./scripts/prebuild.sh"

[target.'cfg(target_arch = "arm")']
pre-build = "./scripts/prebuild.sh"

[target.'cfg(target_arch = "i686")']
pre-build = "./scripts/prebuild.sh"
