[package]
name = "downapk"
version = "0.1.2"
edition = "2021"
categories = ["command-line-utilities"]
description = "Program to download APKs of given Android package"
homepage = "https://github.com/rabilrbl/downapk"
keywords = ["apk", "android", "download", "cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rabilrbl/downapk"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
reqwest = { version = "0.11" }
scraper = "0.18.1"
serde_json = "1.0.111"
tokio = { version = "1.35", features = ["full"] }

[target.'cfg(target_arch = "aarch64")']
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
]

[target.'cfg(target_arch = "aarch64")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target_arch = "arm")']
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
]

[target.'cfg(target_arch = "arm")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
