name: Build for arm64

on:
  release:
    types: [created]
  push:
    tags: 
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
            - target: aarch64-unknown-linux-gnu
              filename: downapk-aarch64-linux
            - target: aarch64-linux-android
              filename: downapk-aarch64-android
            - target: armv7-unknown-linux-gnueabihf
              filename: downapk-armv7-linux
            - target: armv7-linux-androideabi
              filename: downapk-armv7-android
            - target: x86_64-linux-android
              filename: downapk-x86_64-android
            - target: x86_64-unknown-linux-gnu
            - target: i686-unknown-linux-gnu
              filename: downapk-i686-linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
           
      - name: Install dependencies
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build ${{ matrix.target }}
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload unix-like binaries to release
        uses: svenstaro/upload-release-action@v2
        if: contains(matrix.target, 'windows') == false
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/downapk
          asset_name: ${{ matrix.filename }}
          tag: ${{ github.ref }}
          file_glob: false
