name: Build for arm64

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
      options: --user root
    permissions:
      contents: write
    strategy:
      matrix:
        include:
            - target: aarch64-unknown-linux-gnu
              filename: downapk-aarch64-linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: nightly
            target: ${{ matrix.target }}
           
      - name: Install dependencies
        run: |
            apt update && apt install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Build for arm64 container
        run: cargo build --release --target ${{ matrix.target }}
        env:
            CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
            CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
            CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++

