name: Build for arm64

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --user root
    permissions:
      contents: write
    strategy:
      matrix:
        include:
            - target: aarch64-unknown-linux-gnu
              filename: downapk-aarch64-linux
            - target: aarch64-linux-android
              filename: downapk-aarch64-android
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: nightly
            target: ${{ matrix.target }}

      - name: Setup toolchain
        run: |
            rustup target add aarch64-unknown-linux-gnu
            rustup toolchain install nightly-aarch64-unknown-linux-gnu
           
      - name: Install dependencies
        run: |
            dnf install -y openssl-devel gcc-c++-aarch64-linux-gnu

      - name: Build for arm64 container
        run: cargo build --release --target ${{ matrix.target }}

