name: Publish to Cargo

on:
  release:
    types: [created]
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "publish"
    environment: Cargo

    steps:
      - uses: actions/checkout@master

      # Use caching to speed up your build
      - name: Cache publish-action bin
        id: cache-publish-action
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-cargo-publish-v1

      - name: Setup cargo
        run: |
          rustup update --no-self-update stable

      - name: Cargo dry run
        run: |
          cargo publish --dry-run
          
      - name: Cargo publish
        if: success()
        run: |
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
